service: aws-node-serverless-project

frameworkVersion: '3'

provider:
  stage: ${self:custom.defaultStage}
  name: aws
  region: ap-northeast-1
  runtime: nodejs16.x

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  defaultStage: local
  webpack:
    includeModules: true
    packager: 'yarn'

functions:
  hello:
    name: hello-lambda-${sls:stage}
    handler: ./src/lambda.handler
    timeout: 5
