service: aws-node-serverless-project

frameworkVersion: '3'

provider:
  stage: ${opt:stage, self:custom.defaultStage}
  name: aws
  region: ap-northeast-1
  runtime: nodejs16.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ses:SendEmail
            - ses:SendRawEmail
          Resource:
            - !Sub arn:aws:ses:ap-northeast-1:${AWS::AccountId}:identity/${param:fromEmailAddress}
            - !Sub arn:aws:ses:ap-northeast-1:${AWS::AccountId}:identity/${param:toEmailAddress}

plugins:
  - serverless-webpack
  - serverless-lift
  - serverless-offline

custom:
  defaultStage: local
  webpack:
    includeModules: true
    packager: 'yarn'

functions:
  hello:
    name: hello-lambda-${sls:stage}
    handler: ./src/lambda.handler
    timeout: 5
    environment:
      ENV: ${file(./env/${self:provider.stage}.json):ENV}

constructs:
  sqs2ses-queue:
    type: queue
    worker:
      handler: src/sqs2ses.handler
      name: ses2ses-${sls:stage}
      timeout: 5
      environment:
        STAGE: ${self:provider.stage}
        REGION: ${self:provider.region}
        SES_IDENTITY_ARN: !Sub arn:aws:ses:ap-northeast-1:${AWS::AccountId}:identity/${param:fromEmailAddress}
    alarm: ${param:fromEmailAddress}
    extensions:
      queue:
        Properties:
          MaximumMessageSize: 1024
